version: "3.8"

services:
  # Frontend service
  frontend:
         build: ./frontend
         ports:
           - 8080:8080
  # Backend service         
  backend:
        build: ./backend
        ports:
          - 4000:3000
        environment:
          PORT: 3000
          MONGODB_URI: mongodb://db_container:27017
          DB_NAME: infamainsurance
          NAME: makobongo
        depends_on:
          - mongodb
          
#   # Mongodb services
  mongodb:
        container_name: db_container
        image: mongo
        restart: always
        volumes:
          - mongo_db:/data/db

# # volume
volumes:
  mongo_db: {}