version: "3.8"

services:
  frontend:
         build: ./frontend
         ports:
           - 8080:8080
  backend:
        build: ./backend
        ports:
          - 3000:3000
#         environment:
#           DB_URL: mongodb://database/infamainsurance
#   database:
#           image: mongo:4.0-xenial
#           ports:
#             - 27017:27017
#           volumes:
#             - infamainsurance:/data/db

# volumes:
# infamainsurance: